//
//  Helper.swift
//  WarnerMedia Privacy Test App
//
//  Created by T Carr on 6/2/21.
//  Copyright © 2021 T Carr. All rights reserved.
//

import Foundation

class Helper: ObservableObject {
    @Published var showOneTrust: Bool // = false
//    @Published var languagesMap: [languageDetails] = defaults.object(forKey: "languagesMap") as? [languageDetails] ?? [languageDetails(language: "Arabic", code: "ar", isFavorite: false), languageDetails(language: "Bulgarian", code: "bg", isFavorite: false), languageDetails(language: "Croatian", code: "hr", isFavorite: false), languageDetails(language: "Czech", code: "cz", isFavorite: false), languageDetails(language: "Danish", code: "da", isFavorite: false), languageDetails(language: "Dutch", code: "nl", isFavorite: false), languageDetails(language: "English", code: "en-US",isFavorite: true), languageDetails(language: "Finnish", code: "fi",isFavorite: false), languageDetails(language: "French", code: "fr", isFavorite: false), languageDetails(language: "German", code: "de", isFavorite: false), languageDetails(language: "Hungarian", code: "hu", isFavorite: false), languageDetails(language: "Italian", code: "it", isFavorite: false), languageDetails(language: "Norwegian", code: "no", isFavorite: false), languageDetails(language: "Polish", code: "pl", isFavorite: false), languageDetails(language: "Portuguese (Brazil)", code: "pr-BR", isFavorite: false), languageDetails(language: "Portuguese (Portugal)", code: "pt",isFavorite: false), languageDetails(language: "Romanian", code: "ro", isFavorite: false), languageDetails(language: "Russian", code: "ru",isFavorite: false), languageDetails(language: "Slovak", code: "sk", isFavorite: false), languageDetails(language: "Slovenian", code: "sl", isFavorite: false), languageDetails(language: "Spanish (EU)", code: "es", isFavorite: false), languageDetails(language: "Spanish (LatAm)", code: "es-MX", isFavorite: false), languageDetails(language: "Swedish", code: "sv", isFavorite: false), languageDetails(language: "Turkish", code: "tr", isFavorite: false)]
    @Published var languagesMap: [String: languageDetails] // = defaults.object(forKey: "languagesMap") as? [String : languageDetails] ?? ["Arabic": languageDetails(code: "ar", isFavorite: false), "Bulgarian": languageDetails(code: "bg", isFavorite: false), "Croatian": languageDetails(code: "hr", isFavorite: false), "Czech": languageDetails(code: "cz", isFavorite: false), "Danish": languageDetails(code: "da", isFavorite: false), "Dutch": languageDetails(code: "nl", isFavorite: false), "English": languageDetails(code: "en-US",isFavorite: true), "Finnish": languageDetails(code: "fi",isFavorite: false), "French": languageDetails(code: "fr", isFavorite: false), "German": languageDetails(code: "de", isFavorite: false), "Hungarian": languageDetails(code: "hu", isFavorite: false), "Italian": languageDetails(code: "it", isFavorite: false), "Norwegian": languageDetails(code: "no", isFavorite: false), "Polish": languageDetails(code: "pl", isFavorite: false), "Portuguese (Brazil)": languageDetails(code: "pr-BR", isFavorite: false), "Portuguese (Portugal)": languageDetails(code: "pt",isFavorite: false), "Romanian": languageDetails(code: "ro", isFavorite: false), "Russian": languageDetails(code: "ru",isFavorite: false), "Slovak": languageDetails(code: "sk", isFavorite: false), "Slovenian": languageDetails(code: "sl", isFavorite: false), "Spanish (EU)": languageDetails(code: "es", isFavorite: false), "Spanish (LatAm)": languageDetails(code: "es-MX", isFavorite: false), "Swedish": languageDetails(code: "sv", isFavorite: false), "Turkish": languageDetails(code: "tr", isFavorite: false)]
    @Published var dns: Bool // = false

    init(otStatus: Bool) {
        showOneTrust = otStatus
        dns = defaults.object(forKey: "donotSell") as? Bool ?? false
        languagesMap = defaults.object(forKey: "languagesMap") as? [String: languageDetails] ?? ["Arabic": languageDetails(code: "ar", isFavorite: false), "Bulgarian": languageDetails(code: "bg", isFavorite: false), "Croatian": languageDetails(code: "hr", isFavorite: false), "Czech": languageDetails(code: "cz", isFavorite: false), "Danish": languageDetails(code: "da", isFavorite: false), "Dutch": languageDetails(code: "nl", isFavorite: false), "English": languageDetails(code: "en-US", isFavorite: false), "Finnish": languageDetails(code: "fi", isFavorite: false), "French": languageDetails(code: "fr", isFavorite: false), "German": languageDetails(code: "de", isFavorite: false), "Hungarian": languageDetails(code: "hu", isFavorite: false), "Italian": languageDetails(code: "it", isFavorite: false), "Korean": languageDetails(code: "ko", isFavorite: false), "Norwegian": languageDetails(code: "no", isFavorite: false), "Polish": languageDetails(code: "pl", isFavorite: false), "Portuguese (Brazil)": languageDetails(code: "pt-BR", isFavorite: false), "Portuguese (Portugal)": languageDetails(code: "pt", isFavorite: false), "Romanian": languageDetails(code: "ro", isFavorite: false), "Russian": languageDetails(code: "ru", isFavorite: false), "Slovak": languageDetails(code: "sk", isFavorite: false), "Slovenian": languageDetails(code: "sl", isFavorite: false), "Spanish (EU)": languageDetails(code: "es", isFavorite: false), "Spanish (LatAm)": languageDetails(code: "es-MX", isFavorite: false), "Swedish": languageDetails(code: "sv", isFavorite: false), "Turkish": languageDetails(code: "tr", isFavorite: false)]

        languagesMap[systemLanguage]?.isFavorite = true
    }
}
